#设置服务器的端口号
server:
  port: 8080
#数据库连接设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.150.116:3306/EnjoyFitness?userSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis:
#  mapper-locations:

#配置MyBatis

mybatis:
  type-aliases-package: com.qfedu.entity
  mapper-locations: classpath:mapper/*.xml